const allergies = [
    "None",
    "Dust mites",
    "Pet dander",
    "Pollen",
    "Mold",
    "Food allergies",
    "Latex allergy",
    "Bee sting allergy",
    "Drug allergies",
    "Animal dander",
    "Cockroach allergens",
    "Mold spores",
    "Perennial allergic rhinitis",
    "Seasonal allergic rhinitis",
    "Atopic dermatitis",
    "Contact dermatitis",
    "Hives",
    "Anaphylaxis",
    "Food intolerance",
    "Eczema",
    "Asthma",
    "Urticaria",
    "Angioedema",
    "Sinusitis",
    "Conjunctivitis",
];

export default allergies;
